### ISSUE TITLE
Add feature to color answer red.

### ISSUE THREAD

**Issue by azetinaprof** [pablgonz/enumext#1]
Can you add the feature to shade the answer red instead of putting a symbol? 

You can probably create a \setenumext[keyansitem]{colorall={red}} where colorall colors the entire item, then you can also have another option to only color the item number say \setenumext[keyansitem]{colorenum={red}}.

See my question: https://tex.stackexchange.com/q/730032/10898

**Comment by pablgonz** [comment]
@azetinaprof  Hi, thanks for the request, color handling was in an early stage of development, but the idea was to not depend on `xcolor` and use the interface provided by `expl3`, unfortunately they are not compatible with each other, so I'm leaving it aside.

Focusing on the request, I think it is possible to add a `wrap-ans*={code #1}` key that allows to place `\textcolor{red}{#1}` and color the label, overwriting the `wrap-label` key, although it would require duplicating some code, but that's the least of it.

I don't like coloring <code>&langle;item content&rangle;</code>, that is, <code>&langle;label&rangle;</code> next to the <code>&langle;text&rangle;</code> very much and it's not that simple to do, although it's not impossible (I think), from my perspective it's very overemphasized and if there's more than one line with math it looks a bit ugly.

I'll think about this and see how to add it in the next version.

**Comment by pablgonz** [comment]
Full implement in version 1.1 https://github.com/pablgonz/enumext/commit/d2a1379224d4e3b8d1d3bc098a751fce3957dd47
