### ISSUE TITLE
margin label of item

### ISSUE THREAD

**Issue by azetinaprof** [pablgonz/enumext#2]
A nice feature to addi sto extend the symbol component of items. Add a feature such that we can add text as a symbol and we can edit the components as well. For example,

```latex
\begin{enumext}[save-ans=test2024,show-ans=true]
		\item*[\footnotesize\color{red}8.5a, KSC] sample			
			\begin{keyans}
				\item* answer
				\item sample
				\item sample
				\item sample
			\end{keyans}
		\item sample
	\end{enumext}
```

In the sample above, it would be nice to have key values for 8.5a, KSC that allows me to add text with different formats. 

For context, 8.5a, KSC means objective 8.5a level KSC where this means knowledge, simple computation.

It would be nice to tie this to the enumerate label such that when you print answers, it also can print the objective of the question and the level of the question. so that if you do `\printkeyans{test2024}` you get

1 A (8.5, KSC)

```latex
\begin{enumext}[save-ans=test2024,show-ans=true]
		\item*[\footnotesize\color{red}8.5a, KSC] sample			
			\begin{keyans}
				\item* answer
				\item sample
				\item sample
				\item sample
			\end{keyans}
		\item sample
	\end{enumext}
```

It would be nice to have something like
```latex
\item*[obj=8.5a, level = KSC]
```

and we can print 

1 8.5, KSC

**Comment by pablgonz** [comment]
@azetinaprof  An interface for what you want using `\item*[keys]` is not within the scope of this package.

Deliberately no tools are provided for setting scores or ratings, the idea is to make tasks simple and if necessary create your own commands to make adjustments (without touching the internal implementation)

However, in version 1.1 (available tomorrow or the day after) new keys were implemented and example 6 covers this case.
